import { ReactNode, createContext, useContext } from "react";

export interface CompDoc {
    // name: string; // Nama
    // extra: string; // Ekstrakurikuler
    // regCode: string; // Link pendaftaran
    // booklet: string; // Link Juknis
    // hue: number; // HUE Shifts
    // level: number; // Tingkat pendidikan
    // description: string; // Deskripsi
    // price: number; // HTM
    // cp: string; // Contact Person

    name: string,
    extra: string,
    regCode: string,
    description: string,
    form: string,
    booklet: string,
    edu: string,
    level: number,
    hue: number,
    price: number,
    cp: string,
    cpFull: string,
    hx: Array<number>,
}

interface DataProviderProps {
    children: ReactNode;
}

interface DataContextProps {
    data: Array<CompDoc> | null;
}

export const DataContext = createContext<DataContextProps>({
    data: [{
        name: "",
        extra: "",
        regCode: "",
        description: "",
        form: "",
        booklet: "",
        edu: "",
        level: 0,
        hue: 0,
        price: 0,
        cp: "",
        cpFull: "",
        hx: [],
    }],
});

export function DataProvider({ children }: DataProviderProps) {
    // const data = [

    //     {
    //         name: "Band",
    //         extra: "Band",
    //         regCode: "band",
    //         booklet: "https://github.com",
    //         hue: 0,
    //         level: 0,
    //         description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis optio at nisi totam omnis earum vel, ut suscipit doloremque maxime perferendis magnam harum eligendi molestiae sapiente quasi molestias facilis est.\n Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore maiores sapiente, maxime voluptas, voluptates dolore officiis praesentium in illum asperiores quam quod veniam saepe sequi quas. Quisquam quae corporis numquam?\n Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, itaque? Adipisci impedit commodi possimus neque. Temporibus quidem aut fugiat, nulla possimus quia exercitationem odio assumenda ad ab. Quaerat, amet ut.",
    //         // description: "asdasd",
    //         price: 180000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Basket 5v5",
    //         extra: "Basket",
    //         regCode: "basket_5v5",
    //         booklet: "https://github.com",
    //         hue: 30,
    //         level: 0,
    //         description:
    //             "Standard 5-on-5 basketball tournament focused on strategy and skill.",
    //         price: 300000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Film Pendek",
    //         extra: "Cinematography",
    //         regCode: "film_pendek",
    //         booklet: "https://github.com",
    //         hue: 300,
    //         level: 1,
    //         description:
    //             "Short film competition to express creativity and storytelling through video.",
    //         price: 40000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Mobile Legends",
    //         extra: "E-Sports",
    //         regCode: "mlbb",
    //         booklet: "https://github.com",
    //         hue: 200,
    //         level: 0,
    //         description: "Mobile Legends tournament for strategic team-based gameplay.",
    //         price: 100000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Futsal",
    //         extra: "Futsal",
    //         regCode: "futsal",
    //         booklet: "https://github.com",
    //         hue: 40,
    //         level: 1,
    //         description:
    //             "Indoor football competition requiring teamwork and fast reflexes.",
    //         price: 250000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Kriya",
    //         extra: "IPCA",
    //         regCode: "kriya",
    //         booklet: "https://github.com",
    //         hue: 110,
    //         level: 1,
    //         description:
    //             "Handicraft and creative design contest showcasing artistic talent.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Coswalk",
    //         extra: "Japanese Club",
    //         regCode: "coswalk",
    //         booklet: "https://github.com",
    //         hue: 330,
    //         level: 0,
    //         description:
    //             "Cosplay walking performance blending costume and character acting.",
    //         price: 70000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Roket Air",
    //         extra: "KIR",
    //         regCode: "roket_air",
    //         booklet: "https://github.com",
    //         hue: 180,
    //         level: 0,
    //         description:
    //             "Water rocket engineering competition to test physics and creativity.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Modern Dance",
    //         extra: "Modern Dance",
    //         regCode: "modern_dance",
    //         booklet: "https://github.com",
    //         hue: 270,
    //         level: 10,
    //         description:
    //             "Choreographed modern dance competition with expressive movement.",
    //         price: 150000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Olimpiade",
    //         extra: "Olimpiade",
    //         regCode: "olimpiade",
    //         booklet: "https://github.com",
    //         hue: 120,
    //         level: 21,
    //         description: "Academic olympiad testing knowledge and critical thinking.",
    //         price: 50000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Pidato Impromptu",
    //         extra: "Opini",
    //         regCode: "pidato",
    //         booklet: "https://github.com",
    //         hue: 25,
    //         level: 1,
    //         description:
    //             "Spontaneous speech competition focusing on articulation and logic.",
    //         price: 50000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Solo Song",
    //         extra: "Paduan Suara",
    //         regCode: "solo_song",
    //         booklet: "https://github.com",
    //         hue: 0,
    //         level: 0,
    //         description:
    //             "Solo singing competition judged on vocal quality and expression.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "LKBB VARFOR",
    //         extra: "Paskibra",
    //         regCode: "lkbb",
    //         booklet: "https://github.com",
    //         hue: 190,
    //         level: 10,
    //         description:
    //             "Marching and formation competition testing discipline and coordination.",
    //         price: 300000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "PMR Tandu Darurat",
    //         extra: "PMR",
    //         regCode: "pmr_td",
    //         booklet: "https://github.com",
    //         hue: 50,
    //         level: 0,
    //         description: "First aid competition focused on emergency stretcher handling.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "PMR Pertolongan Pertama",
    //         extra: "PMR",
    //         regCode: "pmr_pp",
    //         booklet: "https://github.com",
    //         hue: 50,
    //         level: 0,
    //         description: "Basic first aid simulation showcasing response accuracy.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Senam Pramuka",
    //         extra: "Pramuka",
    //         regCode: "pramuka_senam",
    //         booklet: "https://github.com",
    //         hue: 85,
    //         level: 1,
    //         description: "Scout gymnastics with synchronized movements and energy.",
    //         price: 65000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Miniatur Pioneering Pramuka",
    //         extra: "Pramuka",
    //         regCode: "pramuka_miniatur_pioneering",
    //         booklet: "https://github.com",
    //         hue: 95,
    //         level: 0,
    //         description:
    //             "Miniature pioneering construction challenge using scouting techniques.",
    //         price: 65000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Dharmawacana Hindu",
    //         extra: "Rohin",
    //         regCode: "dharmawacana_hindu",
    //         booklet: "https://github.com",
    //         hue: 305,
    //         level: 1,
    //         description: "Hindu religious speech focusing on values and philosophy.",
    //         price: 30000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Hafalan Doa Hindu",
    //         extra: "Rohin",
    //         regCode: "hafalan_doa_hindu",
    //         booklet: "https://github.com",
    //         hue: 305,
    //         level: 0,
    //         description:
    //             "Hindu prayer recitation test highlighting memorization and fluency.",
    //         price: 30000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Dai/Da’iyah",
    //         extra: "Rohis",
    //         regCode: "dai_daiyah",
    //         booklet: "https://github.com",
    //         hue: 340,
    //         level: 1,
    //         description: "Islamic preaching competition focusing on persuasive delivery.",
    //         price: 60000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Tahfidz",
    //         extra: "Rohis",
    //         regCode: "tahfidz",
    //         booklet: "https://github.com",
    //         hue: 340,
    //         level: 1,
    //         description:
    //             "Qur’an memorization competition focusing on accuracy and tajwid.",
    //         price: 60000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Solo Song Rohani",
    //         extra: "Rokris",
    //         regCode: "solo_song_rohani",
    //         booklet: "https://github.com",
    //         hue: 340,
    //         level: 0,
    //         description:
    //             "Christian solo song contest based on vocal expression and message.",
    //         price: 35000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Storytelling",
    //         extra: "English Club",
    //         regCode: "storytelling",
    //         booklet: "https://github.com",
    //         hue: 290,
    //         level: 0,
    //         description:
    //             "English storytelling contest emphasizing creativity and delivery.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Poster Digital",
    //         extra: "Solusi",
    //         regCode: "poster_digital",
    //         booklet: "https://github.com",
    //         hue: 160,
    //         level: 0,
    //         description:
    //             "Digital poster design contest focusing on aesthetics and message.",
    //         price: 65000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Tari Kreasi",
    //         extra: "Traditional Dance",
    //         regCode: "tari_kreasi",
    //         booklet: "https://github.com",
    //         hue: 210,
    //         level: 10,
    //         description: "Creative traditional dance performance with cultural elements.",
    //         price: 65000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Baca Puisi",
    //         extra: "Teater Pena",
    //         regCode: "baca_puisi",
    //         booklet: "https://github.com",
    //         hue: 270,
    //         level: 0,
    //         description: "Poetry reading competition judged on emotion and articulation.",
    //         price: 50000,
    //         cp: "082281019574",
    //     },
    // ];

    const data = [
        {
            "name": "Band",
            "extra": "Band",
            "regCode": "band",
            "description": "Kompetisi Band memberikan kesempatan bagi siswa SMA untuk tampil di panggung besar dengan membawakan dua lagu bebas—satu wajib dan satu pilihan—selama total 10 menit. Setiap grup, yang terdiri dari 4-6 orang, harus menunjukkan harmoni musik melalui permainan gitar, drum, bass, dan vokal yang apik, ditambah aksi panggung yang energetik untuk menghibur penonton. Mereka bebas mengaransemen ulang lagu atau membawakan karya orisinal, asalkan sesuai dengan tema SAVOR 2025 yang penuh semangat muda. Juri akan menilai kualitas musik, kekompakan tim, dan interaksi dengan audiens. Acara ini selalu jadi favorit karena membawa suasana konser yang meriah dan penuh talenta!",
            "form": "https://forms.gle/zGg3cceMXWtYBQnEA",
            "booklet": "https://drive.google.com/file/d/1Hr1VWWtpiw5iZD2jwygMAFsHkbof1_El/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 0,
            "price": 180000,
            "cp": "85279203763",
            "cpFull": "085279203763",
            "hx": [5]
        },
        {
            "name": "Basket 5v5",
            "extra": "Basketball",
            "regCode": "basket_5v5",
            "description": "Lomba Basket 5v5 dalam SAVOR 2025 adalah kompetisi olahraga bola basket yang mempertemukan tim-tim SMA dari berbagai sekolah di Provinsi Lampung untuk saling unjuk kemampuan di lapangan. Setiap tim terdiri dari 10 hingga 12 pemain, dengan 5 pemain utama yang akan bertanding dalam pertandingan penuh aksi dan strategi. Kompetisi ini menggunakan sistem gugur, sehingga setiap pertandingan menjadi sangat menentukan—tim yang kalah akan langsung tersingkir, sementara pemenang melaju menuju babak berikutnya hingga final untuk memperebutkan gelar juara. Peserta akan ditantang untuk menunjukkan keterampilan menggiring bola, mengoper, dan menembak ke ring lawan, sambil menjaga kerja sama tim yang erat dan stamina yang prima. Selain itu, sportivitas menjadi nilai utama, karena para pemain harus saling menghormati baik dalam kemenangan maupun kekalahan. Acara ini selalu dinantikan karena membawa suasana kompetitif yang seru dan penuh semangat!",
            "form": "https://forms.gle/9f9R4bmBFdP1emzM6",
            "booklet": "https://drive.google.com/file/d/16Nan63rq7CmJFGtO-Di9ZkK2aWH7l6kn/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 30,
            "price": 500000,
            "cp": "81539347721",
            "cpFull": "081539347721",
            "hx": [0, 1, 2, 3]
        },
        {
            "name": "Film Pendek",
            "extra": "Cinematography",
            "regCode": "film_pendek",
            "description": "Lomba Film Pendek mengajak siswa SMA untuk berkolaborasi dalam tim kecil membuat video berdurasi 5-7 menit dengan cerita yang orisinal dan bermakna. Peserta harus menguasai berbagai aspek produksi—menulis naskah, mengarahkan adegan, berakting, merekam, dan menyunting—untuk menghasilkan film yang bisa menyentuh hati atau menginspirasi penonton. Tema bebas, tetapi sering kali mengangkat isu remaja, persahabatan, atau harapan, disampaikan dengan gaya visual dan audio yang kreatif. Film akan dinilai berdasarkan alur cerita, kualitas teknis, dan kekuatan pesan yang disampaikan. Kompetisi ini adalah panggung bagi calon sineas muda untuk menunjukkan bakat mereka dan membawa pulang penghargaan di SAVOR 2025.",
            "form": "https://forms.gle/LGqoi65VM9zHwXNE8",
            "booklet": "https://drive.google.com/file/d/1YVypV8YZAumlT0oYO6qdh_CU87TI85fI/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 300,
            "price": 50000,
            "cp": "88286202249",
            "cpFull": "088286202249",
            "hx": [8]
        },
        {
            "name": "Mobile Legends",
            "extra": "E-Sports",
            "regCode": "mlbb",
            "description": "Kompetisi MLBB E-Sports adalah ajang bergengsi bagi siswa SMA penggemar game Mobile Legends: Bang Bang, sebuah permainan strategi daring yang sangat populer di kalangan anak muda. Setiap tim terdiri dari 6 pemain—5 pemain inti dan 1 cadangan—yang akan bertarung melawan tim lain dalam pertandingan seru untuk menghancurkan basis musuh. Dalam game ini, peserta harus pintar memilih hero, merancang strategi tim, dan berkoordinasi dengan baik untuk mengalahkan lawan, mulai dari menyerang turret hingga menghadapi hero musuh yang kuat. Pertandingan diadakan secara daring pada babak penyisihan dan langsung di panggung utama untuk babak final, sehingga para penonton bisa merasakan ketegangan dan antusiasme yang tercipta. Kompetisi ini tidak hanya menguji keterampilan bermain game, tetapi juga kemampuan berpikir cepat, kerja sama, dan ketahanan mental dalam situasi sulit. Bagi pecinta e-sports, ini adalah kesempatan emas untuk menunjukkan bakat mereka di hadapan publik!",
            "form": "https://forms.gle/M1yrX1giNPaP7dMX8",
            "booklet": "https://drive.google.com/file/d/1gNL0TBdhpS73mWbGbNsagnjrBVayA56U/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 200,
            "price": 120000,
            "cp": "85783894030",
            "cpFull": "085783894030",
            "hx": [0, 1, 3]
        },
        {
            "name": "Futsal",
            "extra": "Futsal",
            "regCode": "futsal",
            "description": "Lomba Futsal adalah kompetisi olahraga yang mempertemukan tim SMP dalam pertandingan cepat dan penuh strategi di lapangan indoor. Setiap tim terdiri dari 7-10 pemain, dengan 5 pemain inti yang akan bertanding dalam sistem gugur—kalah sekali langsung pulang, menang lanjut ke babak berikutnya. Peserta harus menunjukkan keterampilan menggiring bola, mengoper, dan mencetak gol, sambil menjaga stamina dan kerja sama tim di tengah permainan yang intens. Sportivitas juga menjadi fokus, karena setiap tim diharapkan bermain dengan semangat dan saling menghormati. Kompetisi ini selalu membawa energi tinggi dan sorak sorai penonton, menjadikannya penutup yang sempurna untuk rangkaian acara SAVOR 2025.",
            "form": "https://forms.gle/VsczQtgtoF8Vdr6EA",
            "booklet": "https://drive.google.com/file/d/1jRoc-6YFzN0UQq7SZC4kPNXjTic1N4o3/view?usp=drive_link",
            "edu": "SMP",
            "level": 1,
            "hue": 40,
            "price": 250000,
            "cp": "85832750891",
            "cpFull": "085832750891",
            "hx": [5, 6, 7, 8]
        },
        {
            "name": "Kriya",
            "extra": "IPCA",
            "regCode": "kriya",
            "description": "Kompetisi Kriya mengajak siswa SMA untuk menunjukkan kepiawaian mereka dalam membuat kerajinan tangan yang indah dan bernilai seni tinggi. Peserta bebas memilih bahan—kayu, kain, kertas, atau bahkan barang daur ulang—untuk menciptakan karya seperti miniatur, aksesori, atau dekorasi yang mencerminkan kreativitas mereka. Setiap karya harus memiliki sentuhan budaya lokal, misalnya motif Lampung pada anyaman atau ukiran tradisional, sehingga tidak hanya cantik tetapi juga bermakna. Proses pembuatan akan dilakukan di tempat dengan waktu terbatas, sehingga peserta harus cepat, teliti, dan inovatif dalam menghasilkan karya terbaik. Ini adalah ajang yang memadukan keterampilan tangan, imajinasi, dan kepekaan terhadap warisan budaya, menjadikannya salah satu kompetisi yang paling dinanti.",
            "form": "https://forms.gle/Py6EzscrbDrfMTuC7",
            "booklet": "https://drive.google.com/file/d/1LwnPjJ6Q5ZfekZYMsU53O8hJp1nf0P5l/view?usp=drive_link",
            "edu": "SMP",
            "level": 1,
            "hue": 110,
            "price": 75000,
            "cp": "8.95339E+11",
            "cpFull": "0895339111022",
            "hx": [8]
        },
        {
            "name": "Coswalk",
            "extra": "Japanese Club",
            "regCode": "coswalk",
            "description": "Cosplay Walk adalah kompetisi yang ditunggu-tunggu oleh penggemar budaya pop Jepang, khususnya siswa SMA yang suka tampil sebagai karakter favorit dari anime, game, atau tokusatsu. Peserta akan berjalan di atas panggung seperti peragaan busana, memamerkan kostum yang mereka buat sendiri—mulai dari detail kecil seperti aksesori hingga replika senjata atau properti khas karakter. Mereka juga harus berakting sesuai kepribadian karakter tersebut, misalnya berpose dramatis atau menirukan dialog ikonik, sehingga penonton benar-benar merasa karakter itu “hidup”. Penilaian didasarkan pada kreativitas kostum, kemiripan dengan karakter asli, dan penampilan panggung yang percaya diri. Kompetisi ini tidak hanya tentang berdandan, tetapi juga tentang menghormati karya seni yang menginspirasinya, menjadikannya salah satu acara paling meriah dan penuh warna di SAVOR 2025.",
            "form": "https://forms.gle/5fAWvMj3NGbXwDVx6",
            "booklet": "https://drive.google.com/file/d/1C5f3Um73pCC8mX6Gf5DxlDlXWDUnx3ZQ/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 330,
            "price": 70000,
            "cp": "83809532175",
            "cpFull": "083809532175",
            "hx": [5]
        },
        {
            "name": "Roket Air",
            "extra": "KIR",
            "regCode": "roket_air",
            "description": "Kompetisi Roket Air adalah ajang seru yang menggabungkan sains dan kreativitas, di mana siswa SMA merancang roket dari botol plastik yang diluncurkan dengan tekanan air dan udara. Peserta harus memahami prinsip fisika seperti aerodinamika dan tekanan untuk membuat roket yang bisa terbang jauh dan akurat menuju target. Setiap tim akan diberi waktu untuk merakit dan menguji roket mereka sebelum peluncuran resmi, yang selalu menjadi momen paling dinanti karena penuh kejutan—ada roket yang melesat lurus, ada pula yang berputar tak terkendali! Juri akan menilai desain, jarak tempuh, dan ketepatan pendaratan. Ini adalah kompetisi yang mengajarkan kerja tim, ketelitian, dan tentu saja, kesenangan bereksperimen dengan teknologi sederhana.",
            "form": "https://forms.gle/2PXx5n9iGup7QRdi9",
            "booklet": "https://drive.google.com/file/d/1opruUr1S2SiyUeu8KuOMfjnAmBgYhJ2S/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 180,
            "price": 75000,
            "cp": "83179925043",
            "cpFull": "083179925043",
            "hx": [3]
        },
        {
            "name": "Modern Dance",
            "extra": "Modern Dance",
            "regCode": "modern_dance",
            "description": "Lomba Tari Modern mengajak tim SMP dan SMA untuk menampilkan tarian energik bertema “Find Your Iconic” dengan koreografi yang dinamis dan penuh gaya. Setiap tim, terdiri dari 4-8 penari, akan tampil selama 5-7 menit dengan kostum kreatif yang mencerminkan tema—bisa pakaian modern, seragam futuristik, atau apa saja yang mendukung penampilan. Gerakan tari harus sinkron, ekspresif, dan mampu menceritakan kisah atau emosi melalui iringan musik pop atau remix yang kekinian. Juri menilai kekompakan, kreativitas, dan daya tarik panggung yang ditampilkan. Ini adalah ajang untuk menunjukkan semangat muda, keberanian berekspresi, dan bakat seni yang memukau penonton.",
            "form": "https://forms.gle/ar9VeRzJ1MJvmpi99",
            "booklet": "https://drive.google.com/file/d/1FH8q7yUi8wd6XquhtjJgWXRMGHdBeXE9/view?usp=drive_link",
            "edu": "SMP & SMA",
            "level": 2,
            "hue": 270,
            "price": 150000,
            "cp": "85832697158",
            "cpFull": "085832697158",
            "hx": [6, 7]
        },
        {
            "name": "Olimpiade",
            "extra": "Olimpiade",
            "regCode": "olimpiade",
            "description": "Olimpiade akademik dalam SAVOR 2025 adalah kompetisi yang menguji kecerdasan dan pengetahuan siswa SMA dalam berbagai bidang studi, seperti matematika, fisika, kimia, biologi, dan bahasa. Peserta akan menghadapi soal-soal yang dirancang untuk menantang logika, kreativitas, dan pemahaman mendalam mereka—mulai dari perhitungan rumit hingga analisis teks—dalam waktu yang terbatas. Kompetisi ini terdiri dari babak penyisihan tertulis dan babak final yang lebih intens, di mana peserta terbaik akan bersaing untuk meraih medali emas. Selain menjadi ajang prestasi, olimpiade ini juga melatih ketahanan mental dan kemampuan berpikir cepat di bawah tekanan. Bagi siswa yang suka tantangan intelektual, ini adalah kesempatan untuk membuktikan diri dan bersinar di antara yang terbaik!",
            "form": "https://forms.gle/U1tKAuqyUUsthaZY6",
            "booklet": "https://drive.google.com/file/d/1KE9-XdPgVC1w7FYpzr_jM0h0ZlrFild7/view?usp=drive_link",
            "edu": "SD & SMP",
            "level": 3,
            "hue": 120,
            "price": 50000,
            "cp": "81273858388",
            "cpFull": "081273858388",
            "hx": [1, 2]
        },
        {
            "name": "Pidato Impromptu",
            "extra": "Opini",
            "regCode": "pidato",
            "description": "Lomba Pidato Impromptu menguji keberanian dan kecerdasan siswa SMA dalam berbicara secara spontan tentang topik yang diberikan saat itu juga oleh juri. Peserta hanya diberi waktu 2-3 menit untuk mempersiapkan ide sebelum berpidato selama 5 menit, menyusun argumen yang logis dan menyampaikannya dengan penuh percaya diri. Topik bisa sangat beragam—mulai dari isu lingkungan, teknologi, hingga pertanyaan ringan seperti “Mengapa musik penting dalam hidup?”—sehingga peserta harus berpikir cepat dan fleksibel. Penilaian fokus pada isi pidato, gaya penyampaian, dan kemampuan memengaruhi pendengar. Kompetisi ini selalu menarik karena menunjukkan bakat alami siswa dalam berbicara di depan umum dan menghadapi situasi tak terduga.",
            "form": "https://forms.gle/ZXQUJ1HxfXzNiuXh6",
            "booklet": "https://drive.google.com/file/d/1IIJM2ixuKTKy2j51Zo3JvI_RV_2U914N/view?usp=drive_link",
            "edu": "SMP",
            "level": 1,
            "hue": 25,
            "price": 50000,
            "cp": "85709034351",
            "cpFull": "085709034351",
            "hx": [6]
        },
        {
            "name": "Solo Song",
            "extra": "Paduan Suara",
            "regCode": "solo_song",
            "description": "Lomba Solo Song adalah panggung bagi siswa SMA yang ingin memamerkan bakat bernyanyi mereka dengan penuh percaya diri di depan penonton dan juri. Peserta akan membawakan satu lagu populer dari daftar yang telah ditentukan, seperti “Apalah Arti Menunggu” karya Raisa atau “Bukan Cinta Biasa” karya Afgan, dengan iringan musik yang mereka pilih sendiri sebelumnya. Penilaian tidak hanya berdasarkan suara yang merdu, tetapi juga bagaimana peserta menghayati lagu, mengekspresikan emosi melalui gerakan tubuh, dan improvisasi untuk membuat penampilan lebih hidup. Durasi penampilan dibatasi 5-7 menit, sehingga peserta harus pintar mengatur waktu agar pesan lagu tersampaikan dengan baik. Kompetisi ini selalu menjadi sorotan karena memberikan hiburan sekaligus inspirasi bagi penonton, sambil membuktikan bahwa musik adalah bahasa universal yang bisa menyentuh hati siapa saja.",
            "form": "https://forms.gle/nY9WzyWD5o1s54cu7",
            "booklet": "https://drive.google.com/file/d/1cv74hRM5XoXErAIXtO3pkxoZUm8wtqmr/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 0,
            "price": 75000,
            "cp": "82175099715",
            "cpFull": "082175099715",
            "hx": [6]
        },
        {
            "name": "LKBB Variasi Formasi",
            "extra": "Paskibra",
            "regCode": "lkbb",
            "description": "Lomba Ketangkasan Baris-Berbaris (LKBB) Variasi Formasi adalah ajang bagi regu SMP dan SMA untuk menampilkan gerakan baris-berbaris yang rapi, disiplin, dan penuh kreativitas di lapangan terbuka. Setiap regu, yang terdiri dari 8-12 orang, harus mengenakan seragam lengkap dan melakukan formasi unik—seperti lingkaran, zigzag, atau simbol tertentu—sambil menjaga kekompakan dan ketepatan langkah. Kompetisi ini menguji kedisiplinan, konsentrasi, dan semangat tim, dengan komandan regu yang memberikan aba-aba lantang untuk mengarahkan gerakan. Penonton selalu terpukau oleh energi dan harmoni yang ditampilkan, menjadikannya salah satu acara yang penuh semangat dan kebanggaan sekolah.",
            "form": "https://forms.gle/cwhD9nBg36mDnG8Q8",
            "booklet": "https://drive.google.com/file/d/1os4XZQ8vp6sTAz3xMNKFxT9Od6pOE71v/view?usp=drive_link",
            "edu": "SMP & SMA",
            "level": 2,
            "hue": 190,
            "price": 300000,
            "cp": "82175089080",
            "cpFull": "082175089080",
            "hx": [3]
        },
        {
            "name": "PMR Tandu Darurat",
            "extra": "PMR",
            "regCode": "pmr_td",
            "description": "Lomba Peragaan Tandu Darurat mengajak anggota PMR SMA untuk membuat tandu darurat dari bahan-bahan terbatas—seperti kayu, tali, atau kain—dalam waktu singkat, lalu mendemonstrasikan penggunaannya dengan mengangkut “korban” dengan aman. Peserta harus kreatif dan cerdas dalam merancang tandu yang kuat namun ringan, serta menunjukkan koordinasi tim yang baik saat menggunakannya. Skenario akan mensimulasikan kondisi darurat, seperti evakuasi dari bencana, sehingga kecepatan dan ketepatan menjadi kunci. Juri menilai kekuatan konstruksi, efisiensi waktu, dan kenyamanan “korban” selama proses. Ini adalah kompetisi yang mengasah keterampilan praktis dan semangat gotong royong, sekaligus memberikan pelajaran berharga tentang pertolongan pertama.",
            "form": "https://forms.gle/nLrxE8toA2sZV2dV9",
            "booklet": "https://drive.google.com/file/d/1kgnaIB-_YECRKtEpb-Y8aD20RAAD9Jzl/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 50,
            "price": 75000,
            "cp": "85658846635",
            "cpFull": "085658846635",
            "hx": [1]
        },
        {
            "name": "PMR Pertolongan Pertama",
            "extra": "PMR",
            "regCode": "pmr_pp",
            "description": "Lomba Peragaan Pertolongan Pertama diperuntukkan bagi anggota PMR SMA yang ingin menunjukkan keterampilan mereka dalam menangani situasi darurat medis. Setiap tim, terdiri dari 3-5 orang, akan menghadapi skenario simulasi—like luka bakar, patah tulang, atau pingsan—dan harus memberikan pertolongan pertama dengan cepat dan tepat menggunakan peralatan standar seperti perban, kain segitiga, atau alat sederhana lainnya. Mereka akan dinilai berdasarkan ketepatan teknik, kerja sama tim, dan ketenangan dalam situasi darurat. Kompetisi ini tidak hanya tentang kemenangan, tetapi juga melatih peserta untuk siap membantu orang lain dalam kehidupan nyata, menjadikannya salah satu ajang yang paling bermakna di SAVOR 2025.",
            "form": "https://forms.gle/QwfecGNe5Zh861248",
            "booklet": "https://drive.google.com/file/d/1oXxYkoccbED4GGyUK-ybMeLbcF65Q2cb/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 50,
            "price": 75000,
            "cp": "8.95383E+11",
            "cpFull": "0895382509408",
            "hx": [1]
        },
        {
            "name": "Senam Pramuka",
            "extra": "Pramuka",
            "regCode": "pramuka_senam",
            "description": "Kompetisi Senam Pramuka mengajak regu SMP untuk menampilkan gerakan senam yang energik dan ceria dalam formasi kelompok, mengenakan seragam pramuka yang rapi. Setiap regu, terdiri dari 6-10 orang, harus menunjukkan kekompakan, kelincahan, dan semangat melalui koreografi yang disusun dengan iringan musik upbeat. Durasi penampilan sekitar 5-6 menit, dan gerakan bisa mencakup lompatan, putaran, atau formasi sederhana yang mencerminkan jiwa pramuka—sehat, aktif, dan bersahabat. Juri akan menilai sinkronisasi, antusiasme, dan kreativitas tim. Ini adalah ajang yang penuh tawa dan semangat, mengajak semua untuk merayakan kesehatan dan kebersamaan.",
            "form": "https://forms.gle/nxQ7HeEhZccmWdSGA",
            "booklet": "https://drive.google.com/file/d/1wNjg3xkGQJVfmR8bzyAeEwN5bO6sdset/view?usp=drive_link",
            "edu": "SMP",
            "level": 1,
            "hue": 85,
            "price": 65000,
            "cp": "87892500548",
            "cpFull": "087892500548",
            "hx": [2]
        },
        {
            "name": "Miniatur Pioneering Pramuka",
            "extra": "Pramuka",
            "regCode": "pramuka_miniatur_pioneering",
            "description": "Lomba Miniatur Pioneering mengajak siswa SMP dan SMA untuk membuat miniatur struktur—like jembatan, menara, atau gerbang—menggunakan tali dan kayu kecil dengan teknik simpul pramuka. Peserta, yang bekerja dalam tim kecil, harus merancang konstruksi yang tidak hanya kokoh tetapi juga estetis, dengan skala yang proporsional dan detail yang rapi. Waktu pembuatan terbatas, sehingga mereka harus cepat, teliti, dan bekerja sama dengan baik untuk menyelesaikan karya sesuai tema yang diberikan. Juri menilai kekuatan struktur, keakuratan teknik, dan nilai seni dari miniatur tersebut. Kompetisi ini menggabungkan keterampilan pramuka, kreativitas, dan ketangkasan, menjadikannya tantangan yang mendidik sekaligus menghibur.",
            "form": "https://forms.gle/dRJFpACNEAuCAGzg8",
            "booklet": "https://drive.google.com/file/d/1YicQriRbUJxCFH9OwWhHCqiHAQk6uXoT/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 95,
            "price": 65000,
            "cp": "82376124318",
            "cpFull": "082376124318",
            "hx": [8]
        },
        {
            "name": "Dharmawacana Hindu",
            "extra": "Rohani Hindu",
            "regCode": "dharmawacana_hindu",
            "description": "Lomba Dharmawacana Rohani Hindu adalah kompetisi yang mengundang siswa SMA untuk menyampaikan ajaran agama Hindu dengan cara yang inspiratif dan mudah dipahami. Peserta akan berbicara selama 7-10 menit tentang topik seperti dharma, karma, atau nilai-nilai kehidupan menurut ajaran Hindu, menggunakan bahasa yang sederhana namun penuh makna. Mereka harus menunjukkan pemahaman mendalam, kepercayaan diri dalam berbicara, dan kemampuan menyentuh hati pendengar dengan cerita atau contoh yang relevan. Penampilan dinilai berdasarkan isi materi, cara penyampaian, dan dampak spiritual yang diberikan. Kompetisi ini bukan hanya tentang berbicara, tetapi juga tentang berbagi kebijaksanaan dan kedamaian, menjadikannya momen yang penuh hikmat di SAVOR 2025.",
            "form": "https://forms.gle/pb8HL5xzvzxee4EPA",
            "booklet": "https://drive.google.com/file/d/1P_KaY118RP2UTxKxwAtOxu0x2fJNe2IO/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 305,
            "price": 50000,
            "cp": "82382322116",
            "cpFull": "082382322116",
            "hx": [7]
        },
        {
            "name": "Hafalan Doa Hindu",
            "extra": "Rohani Hindu",
            "regCode": "hafalan_doa_hindu",
            "description": "Lomba Pelafalan Doa Rohani Hindu mengajak siswa SMA untuk melafalkan doa-doa suci Hindu dengan penuh kekhidmatan dan kebenaran. Peserta akan membawakan doa pilihan, seperti doa Tri Sandhya atau mantra lainnya, dengan durasi maksimal 5 menit, fokus pada ketepatan pengucapan, irama, dan tajwid yang sesuai dengan tradisi Hindu. Mereka juga harus menunjukkan penghayatan spiritual melalui suara dan ekspresi, sehingga doa yang dilafalkan terasa hidup dan bermakna bagi yang mendengar. Juri akan menilai kejernihan suara, pemahaman makna doa, dan suasana khusyuk yang tercipta. Ini adalah ajang untuk menunjukkan kecintaan terhadap ajaran agama dan kemampuan membawa kedamaian melalui kata-kata suci.",
            "form": "https://forms.gle/NvcySkUCti27LwUU7",
            "booklet": "https://drive.google.com/file/d/1FJQaHMa-n7q2wQXaQ9MhzWjSYjd07tst/view?usp=drive_link",
            "edu": "SMP",
            "level": 1,
            "hue": 305,
            "price": 50000,
            "cp": "82382322116",
            "cpFull": "082382322116",
            "hx": [7]
        },
        {
            "name": "Da'i Da'iyah",
            "extra": "Rohani Islam",
            "regCode": "dai_daiyah",
            "description": "Lomba Da’i dan Da’iyah mengundang siswa SMP untuk menyampaikan ceramah Islami yang menginspirasi dengan tema bebas—bisa tentang akhlak, kebaikan, atau kisah teladan dari kehidupan Rasulullah. Peserta akan berbicara selama 7-10 menit, menggunakan bahasa yang sederhana namun penuh makna, dengan gaya penyampaian yang meyakinkan dan hangat untuk menarik perhatian pendengar. Mereka harus menunjukkan pemahaman agama, kemampuan berbicara, dan karisma untuk menyentuh hati audiens. Penilaian fokus pada isi ceramah, cara penyampaian, dan dampak positif yang diberikan. Kompetisi ini adalah panggung untuk berbagi ilmu dan spiritualitas, sekaligus melatih keberanian berdakwah di depan umum.",
            "form": "https://forms.gle/NCXUz8j1ojvC8bxC6",
            "booklet": "https://drive.google.com/file/d/1nzW-CwHfN9y7csm1bBdp6Oj9xl009pvq/view?usp=drive_link",
            "edu": "SMP",
            "level": 1,
            "hue": 340,
            "price": 60000,
            "cp": "81280029925",
            "cpFull": "081280029925",
            "hx": [2]
        },
        {
            "name": "Tahfidz",
            "extra": "Rohani Islam",
            "regCode": "tahfidz",
            "description": "Kompetisi Tahfidz menguji kemampuan siswa SMP dalam menghafal Al-Qur’an, khususnya dari Juz 30 dan surah-surah pilihan seperti Al-Fatihah atau Al-Ikhlas. Peserta akan melafalkan ayat-ayat dengan tartil, memperhatikan tajwid yang benar, dan suara yang merdu selama 5-7 menit, menunjukkan dedikasi mereka dalam mempelajari kitab suci. Penilaian didasarkan pada hafalan yang akurat, pelafalan yang jelas, dan penghayatan spiritual yang terpancar. Kompetisi ini bukan hanya tentang keahlian menghafal, tetapi juga tentang cinta dan kedekatan dengan Al-Qur’an, menjadikannya momen yang penuh keberkahan di SAVOR 2025.",
            "form": "https://forms.gle/oUTLyQsvxozVyN7g7",
            "booklet": "https://drive.google.com/file/d/1NsE4RSP7zqdkbLhSWP5SWLJEldSOpPVq/view?usp=drive_link",
            "edu": "SMP",
            "level": 1,
            "hue": 340,
            "price": 60000,
            "cp": "87895262725",
            "cpFull": "087895262725",
            "hx": [2]
        },
        {
            "name": "Solo Song Rohani",
            "extra": "Rohani Kristen",
            "regCode": "solo_song_rohani",
            "description": "Kompetisi Solo Song Rohani Kristiani adalah panggung khusus bagi siswa SMA yang ingin memuji Tuhan melalui lagu-lagu rohani yang penuh makna. Peserta akan membawakan satu lagu rohani pilihan, seperti “Bagaikan Bejana” atau “Tuhan Penolongku”, dengan durasi maksimal 7 menit, diiringi musik yang telah disiapkan sebelumnya. Mereka harus menyanyi dengan penghayatan yang dalam, menunjukkan kemampuan vokal yang baik, serta menyampaikan pesan spiritual yang bisa dirasakan oleh pendengar—bukan sekadar menyanyi, tetapi juga berbagi iman melalui nada dan lirik. Penampilan dinilai berdasarkan teknik menyanyi, ekspresi emosional, dan kekhidmatan yang tercipta. Acara ini tidak hanya menjadi kompetisi, tetapi juga momen refleksi yang menyentuh hati, baik bagi peserta maupun penonton.",
            "form": "https://forms.gle/fArq4KEz8ZwZzKhj8",
            "booklet": "https://drive.google.com/file/d/16YkxluexWOLI3qdfqKsV2SFwJQMOqhii/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 340,
            "price": 50000,
            "cp": "82181531725",
            "cpFull": "082181531725",
            "hx": [7]
        },
        {
            "name": "Storytelling",
            "extra": "English Club",
            "regCode": "storrytelling",
            "description": "Lomba Storytelling mengajak siswa SMA untuk menjadi pendongeng ulung dengan tema “Can You Hear The Music?”, yang mengundang cerita-cerita kreatif tentang musik dan maknanya dalam kehidupan. Peserta akan tampil dalam dua babak: pertama, membawakan cerita yang telah mereka siapkan sebelumnya, dan kedua, berimprovisasi dengan cerita baru berdasarkan kata-kata acak yang diberikan juri di tempat. Mereka boleh menggunakan kostum sederhana, properti seperti buku atau alat musik kecil, dan gaya bercerita yang theatrical untuk memikat penonton—bisa dengan suara dramatis, gerakan tangan, atau bahkan nada lucu. Durasi setiap penampilan sekitar 5-7 menit, dan juri akan menilai kreativitas, kemampuan berbicara, serta daya tarik cerita yang disampaikan. Ini adalah ajang yang menguji imajinasi dan keberanian berbicara di depan umum, sekaligus menghibur semua yang hadir dengan kisah-kisah tak terduga.",
            "form": "https://forms.gle/1xdVbDVyDziqG9GeA",
            "booklet": "https://drive.google.com/file/d/1ol-U51sRCAbM0vBNztLlT7FPS0VMW92u/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 290,
            "price": 75000,
            "cp": "8.95371E+11",
            "cpFull": "0895370907289",
            "hx": [8]
        },
        {
            "name": "Poster Digital",
            "extra": "Solusi",
            "regCode": "poster_digital",
            "description": "Lomba Poster Digital adalah wadah bagi siswa SMA untuk mengekspresikan ide-ide cerdas mereka dalam bentuk desain visual yang menarik dan informatif. Dengan tema yang akan diumumkan saat pendaftaran, peserta harus membuat poster menggunakan aplikasi desain seperti Canva, Photoshop, atau lainnya, dengan ukuran standar A3 yang jelas dan mudah dibaca. Poster harus memadukan elemen warna, gambar, dan teks secara harmonis untuk menyampaikan pesan yang kuat—misalnya tentang lingkungan, pendidikan, atau semangat pemuda—tanpa terlihat berlebihan. Juri akan menilai kreativitas, kejelasan pesan, dan estetika desain secara keseluruhan. Kompetisi ini sangat cocok bagi mereka yang suka berkarya di dunia digital dan ingin karyanya dilihat serta diapresiasi oleh banyak orang di SAVOR 2025.",
            "form": "https://forms.gle/6jY7t3hWcc9b1V5x7",
            "booklet": "https://drive.google.com/file/d/1foGqZ2bOBa6DOCiDUF9-g_ZNZSlsc9BS/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 160,
            "price": 65000,
            "cp": "85257264599",
            "cpFull": "085257264599",
            "hx": [3]
        },
        {
            "name": "Tari Kreasi",
            "extra": "Traditional Dance",
            "regCode": "tari_kreasi",
            "description": "Tari Kreasi dalam SAVOR 2025 adalah kompetisi seni tari yang mengajak siswa SMP dan SMA untuk berkreasi dengan gerakan tari yang unik namun tetap mengangkat unsur budaya daerah, seperti tarian Lampung atau tradisi Nusantara lainnya. Setiap kelompok terdiri dari 3 hingga 5 penari yang akan tampil selama 4-6 menit di panggung utama, mengenakan kostum yang mencerminkan tema tarian mereka—bisa berupa pakaian tradisional yang dimodifikasi atau desain modern yang tetap nyaman untuk bergerak. Gerakan tari harus energik, harmonis, dan penuh makna, sering kali menceritakan kisah atau menyampaikan pesan tertentu melalui koreografi yang mereka susun sendiri. Juri akan menilai kreativitas, kekompakan tim, serta kemampuan menyatukan budaya lokal dengan sentuhan kekinian. Ini adalah ajang yang sempurna untuk menunjukkan cinta terhadap seni tari dan warisan budaya, sekaligus menginspirasi generasi muda untuk terus melestarikannya.",
            "form": "https://forms.gle/qn9dPD1xtew13mhL9",
            "booklet": "https://drive.google.com/file/d/1Hbl3Lk60xAivO9maN_HNBhxVtVuRYkuU/view?usp=drive_link",
            "edu": "SMP & SMA",
            "level": 2,
            "hue": 210,
            "price": 125000,
            "cp": "82177874504",
            "cpFull": "082177874504",
            "hx": [8]
        },
        {
            "name": "Baca Puisi",
            "extra": "Teater Pena",
            "regCode": "baca_puisi",
            "description": "Lomba Baca Puisi mengundang siswa SMA untuk membawakan puisi bertema “Bara Pemuda-Pemudi” dengan penuh emosi dan ekspresi yang memikat hati. Peserta akan membaca puisi pilihan atau karya sendiri selama 5-7 menit, menggunakan intonasi, jeda, dan gerakan tubuh untuk menghidupkan makna kata-kata—bisa dengan suara lantang penuh semangat atau lembut penuh perasaan. Penilaian didasarkan pada penghayatan, teknik membaca, dan kemampuan menyampaikan pesan puisi kepada penonton. Kompetisi ini adalah perpaduan seni dan jiwa muda, memberikan ruang bagi peserta untuk mengekspresikan pemikiran dan perasaan mereka tentang semangat generasi muda.",
            "form": "https://forms.gle/kX9v1DhN58sutacz7",
            "booklet": "https://drive.google.com/file/d/1eZfAWgrv-YFlpBYRTgS6lXkyeOXLPa9C/view?usp=drive_link",
            "edu": "SMA",
            "level": 0,
            "hue": 270,
            "price": 50000,
            "cp": "85218217952",
            "cpFull": "085218217952",
            "hx": [5]
        },
    ];

    return <DataContext.Provider value={{ data }}>{children}</DataContext.Provider>;
}

export const useData = () => {
    const context = useContext(DataContext);
    if (!context) {
        throw new Error("useData must be used within a DataProvider");
    }
    return context;
};
