import { ReactNode, createContext, useContext } from "react";

export interface CompDoc {
    // name: string; // Nama
    // extra: string; // Ekstrakurikuler
    // regCode: string; // Link pendaftaran
    // booklet: string; // Link Juknis
    // hue: number; // HUE Shifts
    // level: number; // Tingkat pendidikan
    // description: string; // Deskripsi
    // price: number; // HTM
    // cp: string; // Contact Person

    name: string,
    extra: string,
    regCode: string,
    description: string,
    form: string,
    booklet: string,
    edu: string,
    level: number,
    hue: number,
    price: number,
    cp: string,
    cpFull: string,
    hx: Array<number>,
}

interface DataProviderProps {
    children: ReactNode;
}

interface DataContextProps {
    data: Array<CompDoc> | null;
}

export const DataContext = createContext<DataContextProps>({
    data: [{
        name: "",
        extra: "",
        regCode: "",
        description: "",
        form: "",
        booklet: "",
        edu: "",
        level: 0,
        hue: 0,
        price: 0,
        cp: "",
        cpFull: "",
        hx: [],
    }],
});

export function DataProvider({ children }: DataProviderProps) {
    // const data = [

    //     {
    //         name: "Band",
    //         extra: "Band",
    //         regCode: "band",
    //         booklet: "https://github.com",
    //         hue: 0,
    //         level: 0,
    //         description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis optio at nisi totam omnis earum vel, ut suscipit doloremque maxime perferendis magnam harum eligendi molestiae sapiente quasi molestias facilis est.\n Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore maiores sapiente, maxime voluptas, voluptates dolore officiis praesentium in illum asperiores quam quod veniam saepe sequi quas. Quisquam quae corporis numquam?\n Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, itaque? Adipisci impedit commodi possimus neque. Temporibus quidem aut fugiat, nulla possimus quia exercitationem odio assumenda ad ab. Quaerat, amet ut.",
    //         // description: "asdasd",
    //         price: 180000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Basket 5v5",
    //         extra: "Basket",
    //         regCode: "basket_5v5",
    //         booklet: "https://github.com",
    //         hue: 30,
    //         level: 0,
    //         description:
    //             "Standard 5-on-5 basketball tournament focused on strategy and skill.",
    //         price: 300000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Film Pendek",
    //         extra: "Cinematography",
    //         regCode: "film_pendek",
    //         booklet: "https://github.com",
    //         hue: 300,
    //         level: 1,
    //         description:
    //             "Short film competition to express creativity and storytelling through video.",
    //         price: 40000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Mobile Legends",
    //         extra: "E-Sports",
    //         regCode: "mlbb",
    //         booklet: "https://github.com",
    //         hue: 200,
    //         level: 0,
    //         description: "Mobile Legends tournament for strategic team-based gameplay.",
    //         price: 100000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Futsal",
    //         extra: "Futsal",
    //         regCode: "futsal",
    //         booklet: "https://github.com",
    //         hue: 40,
    //         level: 1,
    //         description:
    //             "Indoor football competition requiring teamwork and fast reflexes.",
    //         price: 250000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Kriya",
    //         extra: "IPCA",
    //         regCode: "kriya",
    //         booklet: "https://github.com",
    //         hue: 110,
    //         level: 1,
    //         description:
    //             "Handicraft and creative design contest showcasing artistic talent.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Coswalk",
    //         extra: "Japanese Club",
    //         regCode: "coswalk",
    //         booklet: "https://github.com",
    //         hue: 330,
    //         level: 0,
    //         description:
    //             "Cosplay walking performance blending costume and character acting.",
    //         price: 70000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Roket Air",
    //         extra: "KIR",
    //         regCode: "roket_air",
    //         booklet: "https://github.com",
    //         hue: 180,
    //         level: 0,
    //         description:
    //             "Water rocket engineering competition to test physics and creativity.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Modern Dance",
    //         extra: "Modern Dance",
    //         regCode: "modern_dance",
    //         booklet: "https://github.com",
    //         hue: 270,
    //         level: 10,
    //         description:
    //             "Choreographed modern dance competition with expressive movement.",
    //         price: 150000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Olimpiade",
    //         extra: "Olimpiade",
    //         regCode: "olimpiade",
    //         booklet: "https://github.com",
    //         hue: 120,
    //         level: 21,
    //         description: "Academic olympiad testing knowledge and critical thinking.",
    //         price: 50000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Pidato Impromptu",
    //         extra: "Opini",
    //         regCode: "pidato",
    //         booklet: "https://github.com",
    //         hue: 25,
    //         level: 1,
    //         description:
    //             "Spontaneous speech competition focusing on articulation and logic.",
    //         price: 50000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Solo Song",
    //         extra: "Paduan Suara",
    //         regCode: "solo_song",
    //         booklet: "https://github.com",
    //         hue: 0,
    //         level: 0,
    //         description:
    //             "Solo singing competition judged on vocal quality and expression.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "LKBB VARFOR",
    //         extra: "Paskibra",
    //         regCode: "lkbb",
    //         booklet: "https://github.com",
    //         hue: 190,
    //         level: 10,
    //         description:
    //             "Marching and formation competition testing discipline and coordination.",
    //         price: 300000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "PMR Tandu Darurat",
    //         extra: "PMR",
    //         regCode: "pmr_td",
    //         booklet: "https://github.com",
    //         hue: 50,
    //         level: 0,
    //         description: "First aid competition focused on emergency stretcher handling.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "PMR Pertolongan Pertama",
    //         extra: "PMR",
    //         regCode: "pmr_pp",
    //         booklet: "https://github.com",
    //         hue: 50,
    //         level: 0,
    //         description: "Basic first aid simulation showcasing response accuracy.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Senam Pramuka",
    //         extra: "Pramuka",
    //         regCode: "pramuka_senam",
    //         booklet: "https://github.com",
    //         hue: 85,
    //         level: 1,
    //         description: "Scout gymnastics with synchronized movements and energy.",
    //         price: 65000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Miniatur Pioneering Pramuka",
    //         extra: "Pramuka",
    //         regCode: "pramuka_miniatur_pioneering",
    //         booklet: "https://github.com",
    //         hue: 95,
    //         level: 0,
    //         description:
    //             "Miniature pioneering construction challenge using scouting techniques.",
    //         price: 65000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Dharmawacana Hindu",
    //         extra: "Rohin",
    //         regCode: "dharmawacana_hindu",
    //         booklet: "https://github.com",
    //         hue: 305,
    //         level: 1,
    //         description: "Hindu religious speech focusing on values and philosophy.",
    //         price: 30000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Hafalan Doa Hindu",
    //         extra: "Rohin",
    //         regCode: "hafalan_doa_hindu",
    //         booklet: "https://github.com",
    //         hue: 305,
    //         level: 0,
    //         description:
    //             "Hindu prayer recitation test highlighting memorization and fluency.",
    //         price: 30000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Dai/Da’iyah",
    //         extra: "Rohis",
    //         regCode: "dai_daiyah",
    //         booklet: "https://github.com",
    //         hue: 340,
    //         level: 1,
    //         description: "Islamic preaching competition focusing on persuasive delivery.",
    //         price: 60000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Tahfidz",
    //         extra: "Rohis",
    //         regCode: "tahfidz",
    //         booklet: "https://github.com",
    //         hue: 340,
    //         level: 1,
    //         description:
    //             "Qur’an memorization competition focusing on accuracy and tajwid.",
    //         price: 60000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Solo Song Rohani",
    //         extra: "Rokris",
    //         regCode: "solo_song_rohani",
    //         booklet: "https://github.com",
    //         hue: 340,
    //         level: 0,
    //         description:
    //             "Christian solo song contest based on vocal expression and message.",
    //         price: 35000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Storytelling",
    //         extra: "English Club",
    //         regCode: "storytelling",
    //         booklet: "https://github.com",
    //         hue: 290,
    //         level: 0,
    //         description:
    //             "English storytelling contest emphasizing creativity and delivery.",
    //         price: 75000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Poster Digital",
    //         extra: "Solusi",
    //         regCode: "poster_digital",
    //         booklet: "https://github.com",
    //         hue: 160,
    //         level: 0,
    //         description:
    //             "Digital poster design contest focusing on aesthetics and message.",
    //         price: 65000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Tari Kreasi",
    //         extra: "Traditional Dance",
    //         regCode: "tari_kreasi",
    //         booklet: "https://github.com",
    //         hue: 210,
    //         level: 10,
    //         description: "Creative traditional dance performance with cultural elements.",
    //         price: 65000,
    //         cp: "082281019574",
    //     },
    //     {
    //         name: "Baca Puisi",
    //         extra: "Teater Pena",
    //         regCode: "baca_puisi",
    //         booklet: "https://github.com",
    //         hue: 270,
    //         level: 0,
    //         description: "Poetry reading competition judged on emotion and articulation.",
    //         price: 50000,
    //         cp: "082281019574",
    //     },
    // ];

    const data = [
        {
            "name": "Band",
            "extra": "Band",
            "regCode": "band",
            "description": "Group music performance showcasing musical skill and teamwork.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 0,
            "price": 180000,
            "cp": "85279203763",
            "cpFull": "085279203763",
            "hx": [0]
        },
        {
            "name": "Basket 5v5",
            "extra": "Basketball",
            "regCode": "basket_5v5",
            "description": "Standard 5-on-5 basketball tournament focused on strategy and skill.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 30,
            "price": 300000,
            "cp": "81539347721",
            "cpFull": "081539347721",
            "hx": [0]
        },
        {
            "name": "Film Pendek",
            "extra": "Cinematography",
            "regCode": "film_pendek",
            "description": "Short film competition to express creativity and storytelling through video.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 300,
            "price": 40000,
            "cp": "88286202249",
            "cpFull": "088286202249",
            "hx": [0]
        },
        {
            "name": "Mobile Legends",
            "extra": "E-Sports",
            "regCode": "mlbb",
            "description": "Mobile Legends tournament for strategic team-based gameplay.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 200,
            "price": 100000,
            "cp": "85783894030",
            "cpFull": "085783894030",
            "hx": [0]
        },
        {
            "name": "Futsal",
            "extra": "Futsal",
            "regCode": "futsal",
            "description": "Indoor football competition requiring teamwork and fast reflexes.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMP",
            "level": 1,
            "hue": 40,
            "price": 250000,
            "cp": "85832750891",
            "cpFull": "085832750891",
            "hx": [0]
        },
        {
            "name": "Kriya",
            "extra": "IPCA",
            "regCode": "kriya",
            "description": "Handicraft and creative design contest showcasing artistic talent.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMP",
            "level": 1,
            "hue": 110,
            "price": 75000,
            "cp": "895339111022",
            "cpFull": "0895339111022",
            "hx": [0]
        },
        {
            "name": "Coswalk",
            "extra": "Japanese Club",
            "regCode": "coswalk",
            "description": "Cosplay walking performance blending costume and character acting.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 330,
            "price": 70000,
            "cp": "83809532175",
            "cpFull": "083809532175",
            "hx": [0]
        },
        {
            "name": "Roket Air",
            "extra": "KIR",
            "regCode": "roket_air",
            "description": "Water rocket engineering competition to test physics and creativity.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 180,
            "price": 75000,
            "cp": "83179925043",
            "cpFull": "083179925043",
            "hx": [0]
        },
        {
            "name": "Modern Dance",
            "extra": "Modern Dance",
            "regCode": "modern_dance",
            "description": "Choreographed modern dance competition with expressive movement.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMP & SMA",
            "level": 2,
            "hue": 270,
            "price": 150000,
            "cp": "85832697158",
            "cpFull": "085832697158",
            "hx": [0]
        },
        {
            "name": "Olimpiade",
            "extra": "Olimpiade",
            "regCode": "olimpiade",
            "description": "Academic olympiad testing knowledge and critical thinking.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SD & SMP",
            "level": 3,
            "hue": 120,
            "price": 50000,
            "cp": "81273858388",
            "cpFull": "081273858388",
            "hx": [0]
        },
        {
            "name": "Pidato Impromptu",
            "extra": "Opini",
            "regCode": "pidato",
            "description": "Spontaneous speech competition focusing on articulation and logic.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMP",
            "level": 1,
            "hue": 25,
            "price": 50000,
            "cp": "85709034351",
            "cpFull": "085709034351",
            "hx": [0]
        },
        {
            "name": "Solo Song",
            "extra": "Paduan Suara",
            "regCode": "solo_song",
            "description": "Solo singing competition judged on vocal quality and expression.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 0,
            "price": 75000,
            "cp": "82175099715",
            "cpFull": "082175099715",
            "hx": [0]
        },
        {
            "name": "LKBB Variasi Formasi",
            "extra": "Paskibra",
            "regCode": "lkbb",
            "description": "Marching and formation competition testing discipline and coordination.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMP & SMA",
            "level": 2,
            "hue": 190,
            "price": 300000,
            "cp": "82175089080",
            "cpFull": "082175089080",
            "hx": [0]
        },
        {
            "name": "PMR Tandu Darurat",
            "extra": "PMR",
            "regCode": "pmr_td",
            "description": "First aid competition focused on emergency stretcher handling.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 50,
            "price": 75000,
            "cp": "85658846635",
            "cpFull": "085658846635",
            "hx": [0]
        },
        {
            "name": "PMR Pertolongan Pertama",
            "extra": "PMR",
            "regCode": "pmr_pp",
            "description": "Basic first aid simulation showcasing response accuracy.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 50,
            "price": 75000,
            "cp": "895382509408",
            "cpFull": "0895382509408",
            "hx": [0]
        },
        {
            "name": "Senam Pramuka",
            "extra": "Pramuka",
            "regCode": "pramuka_senam",
            "description": "Scout gymnastics with synchronized movements and energy.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMP",
            "level": 1,
            "hue": 85,
            "price": 65000,
            "cp": "87892500548",
            "cpFull": "087892500548",
            "hx": [0]
        },
        {
            "name": "Miniatur Pioneering Pramuka",
            "extra": "Pramuka",
            "regCode": "pramuka_miniatur_pioneering",
            "description": "Miniature pioneering construction challenge using scouting techniques.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 95,
            "price": 65000,
            "cp": "82376124318",
            "cpFull": "082376124318",
            "hx": [0]
        },
        {
            "name": "Dharmawacana Hindu",
            "extra": "Rohani Hindu",
            "regCode": "dharmawacana_hindu",
            "description": "Hindu religious speech focusing on values and philosophy.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 305,
            "price": 30000,
            "cp": "82382322116",
            "cpFull": "082382322116",
            "hx": [0]
        },
        {
            "name": "Hafalan Doa Hindu",
            "extra": "Rohani Hindu",
            "regCode": "hafalan_doa_hindu",
            "description": "Hindu prayer recitation test highlighting memorization and fluency.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMP",
            "level": 1,
            "hue": 305,
            "price": 30000,
            "cp": "82382322116",
            "cpFull": "082382322116",
            "hx": [0]
        },
        {
            "name": "Da'I Da'iyah",
            "extra": "Rohani Islam",
            "regCode": "dai_daiyah",
            "description": "Lorem Ipsum",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMP",
            "level": 1,
            "hue": 340,
            "price": 60000,
            "cp": "81280029925",
            "cpFull": "081280029925",
            "hx": [0]
        },
        {
            "name": "Tahfidz",
            "extra": "Rohani Islam",
            "regCode": "tahfidz",
            "description": "Qur’an memorization competition focusing on accuracy and tajwid.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMP",
            "level": 1,
            "hue": 340,
            "price": 60000,
            "cp": "87895262725",
            "cpFull": "087895262725",
            "hx": [0]
        },
        {
            "name": "Solo Song Rohani",
            "extra": "Rohani Kristen",
            "regCode": "solo_song_rohani",
            "description": "Christian solo song contest based on vocal expression and message.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 340,
            "price": 35000,
            "cp": "82181531725",
            "cpFull": "082181531725",
            "hx": [0]
        },
        {
            "name": "Storytelling",
            "extra": "English Club",
            "regCode": "storrytelling",
            "description": "English storytelling contest emphasizing creativity and delivery.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 290,
            "price": 75000,
            "cp": "895370907289",
            "cpFull": "0895370907289",
            "hx": [0]
        },
        {
            "name": "Poster Digital",
            "extra": "Solusi",
            "regCode": "poster_digital",
            "description": "Digital poster design contest focusing on aesthetics and message.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 160,
            "price": 65000,
            "cp": "85257264599",
            "cpFull": "085257264599",
            "hx": [0]
        },
        {
            "name": "Tari Kreasi",
            "extra": "Traditional Dance",
            "regCode": "tari_kreasi",
            "description": "Creative traditional dance performance with cultural elements.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMP & SMA",
            "level": 2,
            "hue": 210,
            "price": 125000,
            "cp": "82177874504",
            "cpFull": "082177874504",
            "hx": [0]
        },
        {
            "name": "Baca Puisi",
            "extra": "Teater Pena",
            "regCode": "baca_puisi",
            "description": "Poetry reading competition judged on emotion and articulation.",
            "form": "https://youtube.com",
            "booklet": "https://github.com",
            "edu": "SMA",
            "level": 0,
            "hue": 270,
            "price": 50000,
            "cp": "85218217952",
            "cpFull": "085218217952",
            "hx": [0]
        }
    ];

    return <DataContext.Provider value={{ data }}>{children}</DataContext.Provider>;
}

export const useData = () => {
    const context = useContext(DataContext);
    if (!context) {
        throw new Error("useData must be used within a DataProvider");
    }
    return context;
};
