import HomePage from "@/components/HomePage";
import Landing from "@/components/Landing";
import Head from "next/head";
import { useEffect, useState } from "react";
// import Image from "next/image";
import styles from "@/styles/Roof.module.sass";

export default function Home() {
    const [bigBang, setBigBang] = useState(false);
    const [noLanding, setNoLanding] = useState(false);

    useEffect(() => {
        // Check if big bang has already happened
        const storedBigBang = sessionStorage.getItem("bigBang");
        if (storedBigBang === "true") {
            setBigBang(true);
            setNoLanding(true);
        }
    }, []);

    return (
        <>
            <Head>
                <title>SAVOR 25</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div id="_roof" className={`${styles.roof}`}>
                {/* <h1>{bigBang ? " YES" : "NO"}</h1> */}
                {bigBang && <HomePage />}
                {!noLanding && <Landing bbSetter={setBigBang} />}
            </div>
        </>
    );
}
