import HomePage from "@/components/HomePage";
import Landing from "@/components/Landing";
import Head from "next/head";
import { useState } from "react";
// import Image from "next/image";

export default function Home() {
    const [bigBang, setBigBang] = useState(false);

    return (
        <>
            <Head>
                <title>Antakara 25</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Landing bbSetter={setBigBang} />
                {bigBang && <HomePage />}
            </div>
        </>
    );
}
